[phases.setup]
nixPkgs = ["python312", "zlib", "libjpeg", "libpng", "freetype", "lcms2", "openjpeg", "libtiff", "libwebp"]

[phases.install]
cmds = ["pip install --only-binary=:all: -r requirements.txt"]