[phases.setup]
nixPkgs = [
  "python312Full",
  "pipenv",
  "freetype",
  "lcms2",
  "libjpeg",
  "libpng",
  "libwebp",
  "openjpeg",
  "libtiff",
  "zlib"
]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]
