[phases.setup]
nixPkgs = [
  "python312Full",
  "freetype",
  "lcms2",
  "libjpeg",
  "libpng",
  "libwebp",
  "openjpeg",
  "libtiff",
  "zlib"
]

[phases.install]
cmds = [
  "python3.12 -m ensurepip --upgrade",  # Asegura que pip esté instalado
  "python3.12 -m pip install --upgrade pip setuptools",  # Asegura que pip y setuptools estén actualizados
  "python3.12 -m pip install -r requirements.txt"  # Instalar las dependencias
]