providers = ["python"]

[phases.setup]
nixPkgs = [
 # "python3.11Full",   Usamos la versión completa de Python 3.11
  "python311",
  "freetype",  # Fuentes
  "lcms2",  # Gestión de color
  "libjpeg",  # Imágenes JPEG
  "libpng",  # Imágenes PNG
  "libwebp",  # Imágenes WebP
  "openjpeg",  # JPEG2000
  "libtiff",  # Imágenes TIFF
  "zlib"  # Compresión
]


[phases.postDeploy]
  cmds = [
    "pip install -r requirements.txt",  # Instala las dependencias de requirements.txt
    "python manage.py migrate"          # Corre las migraciones de Django
  ]

[start]
cmd = "gunicorn nuestrotubo.wsgi"