[phases.setup]
nixPkgs = [
  "python311Full",  # Python con pip incluido
  "pip",            # pip explícitamente
  "freetype",
  "lcms2",
  "libjpeg",
  "libpng",
  "libwebp",
  "openjpeg",
  "libtiff",
  "zlib"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]