[phases.setup]
nixPkgs = [
  "python312Full",
  "freetype",
  "lcms2",
  "libjpeg",
  "libpng",
  "libwebp",
  "openjpeg",
  "libtiff",
  "zlib"
]


[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",  # Descarga el script oficial de instalación de pip
  "python3.12 get-pip.py",  # Instala pip usando el script descargado
  "python3.12 -m pip install -r requirements.txt"  # Instala las dependencias de tu proyecto
]