[phases.setup]
nixPkgs = [
 # "python3.11Full",   Usamos la versión completa de Python 3.11
  "python311",
  "freetype",  # Fuentes
  "lcms2",  # Gestión de color
  "libjpeg",  # Imágenes JPEG
  "libpng",  # Imágenes PNG
  "libwebp",  # Imágenes WebP
  "openjpeg",  # JPEG2000
  "libtiff",  # Imágenes TIFF
  "zlib"  # Compresión
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",  # Crea un entorno virtual
  "/opt/venv/bin/python -m pip install --upgrade pip setuptools",  # Instala pip y setuptools dentro del venv
  "/opt/venv/bin/python -m pip install -r requirements.txt"  # Instala las dependencias en el venv
]

[phases.postDeploy]
cmds = ["python manage.py migrate"]

[start]
cmd = "gunicorn nuestrotubo.wsgi"