[phases.setup]
nixPkgs = [
  "python311Full",  # ¡Cambiamos a una versión más estable!
  "freetype",
  "lcms2",
  "libjpeg",
  "libpng",
  "libwebp",
  "openjpeg",
  "libtiff",
  "zlib"
]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip setuptools",
  "python3.11 -m pip install -r requirements.txt"
]
