[phases.setup]
nixPkgs = [
  "python312Full",  # Python 3.12 completo, que incluye pip
  "freetype",  # Fuentes
  "lcms2",  # Gestión de color
  "libjpeg",  # Imágenes JPEG
  "libpng",  # Imágenes PNG
  "libwebp",  # Imágenes WebP
  "openjpeg",  # JPEG2000
  "libtiff",  # Imágenes TIFF
  "zlib"  # Compresión
]

[phases.install]
cmds = [
  "python3.12 -m pip install --upgrade pip setuptools",  # Aseguramos que pip y setuptools estén actualizados
  "python3.12 -m pip install -r requirements.txt"  # Instalamos las dependencias del proyecto
]