[phases.setup]
nixPkgs = [
  "python312.withPackages (ps: with ps; [pip setuptools wheel])",
  "freetype",
  "lcms2",
  "libjpeg",
  "libpng",
  "libwebp",
  "openjpeg",
  "libtiff",
  "zlib"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools",  # Ya no hace falta especificar python3.12
  "pip install -r requirements.txt"
]
