# Generated by Django 5.0.3 on 2024-03-28 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElegidosXSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elegidos_por_semana', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='calorias',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Calórico', 'Calórico'), ('Liviano', 'Liviano'), ('Normal', 'Normal'), ('Plato de invierno', 'Plato de invierno')], default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Común', 'Común'), ('Especial', 'Especial')], default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='medios',
            field=models.CharField(blank=True, choices=[('-', '-'), ('horno', 'horno'), ('cocina', 'cocina'), ('parrilla', 'parrilla'), ('wok', 'wok'), ('sin coccion', 'sin cocción')], default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='preparacion',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Mucho', 'Mucho'), ('Poco', 'Poco'), ('Nada', 'Nada')], default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('-', '-'), ('entrada', 'Entrada'), ('salsa', 'Salsa'), ('picada', 'Picada'), ('Plato principal', 'Plato principal'), ('postre', 'postre'), ('torta', 'torta'), ('untable', 'untable'), ('trago', 'trago'), ('guarnicion', 'guarnicion')], default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='variedades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Subí una imagen que identifique al plato (o un fotograma del mismo)'),
        ),
        migrations.CreateModel(
            name='Elegidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato_elegido', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos_elegidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sugeridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato_sugerido', models.CharField(max_length=30)),
                ('usuario_de_sugeridos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sugeridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
