# Generated by Django 5.0.2 on 2024-02-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elegidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='plato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Subí una imagen que identifique al plato (o un fotograma del mismo)'),
        ),
    ]
