# Generated by Django 5.0.3 on 2024-03-30 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0002_elegidosxsemana_plato_calorias_plato_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elegidosxsemana',
            name='elegidos_por_semana',
        ),
        migrations.AddField(
            model_name='elegidosxsemana',
            name='el_dia_en_que_comemos',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='elegidosxsemana',
            name='plato_que_comemos',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='elegidosxsemana',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_come', to=settings.AUTH_USER_MODEL),
        ),
    ]
