# Generated by Django 4.1.7 on 2024-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0003_elegidospordia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elegidospordia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='elegidospordia',
            name='nombre_plato',
        ),
        migrations.AddField(
            model_name='elegidospordia',
            name='elegidos_por_dia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
