# Generated by Django 5.0.3 on 2024-03-30 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0003_remove_elegidosxsemana_elegidos_por_semana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElegidosXSemana',
            new_name='ElegidosXDia',
        ),
    ]
