# Generated by Django 5.0.3 on 2024-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0004_rename_elegidosxsemana_elegidosxdia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elegidosxdia',
            name='plato_que_comemos',
        ),
        migrations.AddField(
            model_name='elegidosxdia',
            name='platos_que_comemos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
