# Generated by Django 5.0.3 on 2024-03-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0006_alter_elegidosxdia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='descripcion_plato',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='plato',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ingresá los ingredientes, separados por coma'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='receta',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
