# Generated by Django 4.1.7 on 2024-03-13 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminVideos', '0007_remove_elegidos_nombre_plato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elegidos',
            name='usuario_preseleccionados',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elegidos',
            name='nombre_plato_elegido',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
