# Generated by Django 4.1.7 on 2024-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0008_elegidos_usuario_preseleccionados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elegidos',
            name='nombre_plato_elegido',
        ),
        migrations.RemoveField(
            model_name='elegidos',
            name='usuario_preseleccionados',
        ),
        migrations.AddField(
            model_name='elegidos',
            name='nombre_plato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
