# Generated by Django 5.0.3 on 2024-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0008_profile_ingredientes_que_tengo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elegidos',
            name='tipo_plato',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='calorias',
            field=models.CharField(choices=[('-', '-'), ('Calórico', 'Calórico'), ('Liviano', 'Liviano'), ('Normal', 'Normal'), ('Plato de invierno', 'Plato de invierno')], default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('-', '-'), ('Común', 'Común'), ('Especial', 'Especial')], default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='medios',
            field=models.CharField(choices=[('-', '-'), ('horno', 'horno'), ('cocina', 'cocina'), ('parrilla', 'parrilla'), ('wok', 'wok'), ('sin coccion', 'sin cocción')], default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='preparacion',
            field=models.CharField(choices=[('-', '-'), ('Poco', 'Poco'), ('Nada', 'Nada')], default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('-', '-'), ('Entrada', 'Entrada'), ('Salsa', 'Salsa'), ('Picada', 'Picada'), ('Principal', 'Plato Principal'), ('Postre', 'Postre'), ('Torta', 'Torta'), ('Dip', 'Dip'), ('Trago', 'Trago'), ('Guarnicion', 'Guarnicion')], default='-', max_length=20, null=True),
        ),
    ]
