# Generated by Django 4.1.7 on 2024-03-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0009_remove_elegidos_nombre_plato_elegido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elegidos',
            name='nombre_plato',
        ),
        migrations.AddField(
            model_name='elegidos',
            name='nombre_plato_elegido',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
