# Generated by Django 5.0.3 on 2024-11-02 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0009_elegidos_tipo_plato_alter_plato_calorias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elegidos',
            new_name='Preseleccionados',
        ),
    ]
