# Generated by Django 5.0.3 on 2024-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0010_rename_elegidos_preseleccionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comentarios',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
