# Generated by Django 4.1.7 on 2024-03-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0010_remove_elegidos_nombre_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegidos',
            name='nombre_plato_elegido',
            field=models.JSONField(default=list),
        ),
    ]
