# Generated by Django 4.1.7 on 2024-03-13 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminVideos', '0011_alter_elegidos_nombre_plato_elegido'),
    ]

    operations = [
        migrations.AddField(
            model_name='elegidos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos_elegidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
