# Generated by Django 5.0.3 on 2024-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0012_remove_profile_nombre_completo_profile_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preseleccionados',
            old_name='nombre_plato_elegido',
            new_name='nombre_plato_preseleccionado',
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('-', '-'), ('Entrada', 'Entrada'), ('Salsa', 'Salsa'), ('Picada', 'Picada'), ('Principal', 'Plato Principal'), ('Postre', 'Postre'), ('Torta', 'Torta'), ('Dip', 'Dip'), ('Trago', 'Trago'), ('Guarnicion', 'Guarnicion')], max_length=20),
        ),
    ]
