# Generated by Django 4.1.7 on 2024-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0013_alter_elegidos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='calorias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='medios',
            field=models.CharField(blank=True, choices=[('horno', 'horno'), ('cocina', 'cocina'), ('parrilla', 'parrilla'), ('wok', 'wok'), ('sin coccion', 'sin cocción')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salsa', 'Salsa'), ('picada', 'Picada'), ('Plato principal', 'Plato principal'), ('postre', 'postre'), ('torta', 'torta'), ('untable', 'untable'), ('trago', 'trago'), ('guarnicion', 'guarnicion')], max_length=20, null=True),
        ),
    ]
