# Generated by Django 4.1.7 on 2024-03-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0014_plato_calorias_plato_categoria_plato_medios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='preparacion',
            field=models.CharField(blank=True, choices=[('Mucho', 'Mucho'), ('Poco', 'Poco'), ('Nada', 'Nada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='calorias',
            field=models.CharField(blank=True, choices=[('Calórico', 'Calórico'), ('Liviano', 'Liviano'), ('Normal', 'Normal'), ('Plato de invierno', 'Plato de invierno')], max_length=20, null=True),
        ),
    ]
