# Generated by Django 5.1.3 on 2024-11-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0015_rename_nombre_plato_preseleccionado_preseleccionados_nombre_plato_elegido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='email',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='amistad',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='amigues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plato',
            name='calorias',
            field=models.CharField(choices=[('-', '-'), ('Calórico', 'Calórico'), ('Liviano', 'Liviano'), ('Normal', 'Normal'), ('Plato de invierno', 'Plato de invierno')], default='Normal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('-', '-'), ('Común', 'Común'), ('Especial', 'Especial')], default='Común', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='medios',
            field=models.CharField(choices=[('-', '-'), ('Horno', 'Horno'), ('Cocina', 'Cocina'), ('Parrilla', 'Parrilla'), ('Wok', 'Wok'), ('Sin coccion', 'Sin cocción')], default='Cocina', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='preparacion',
            field=models.CharField(choices=[('-', '-'), ('Poco', 'Poco'), ('Nada', 'Nada'), ('Normal', 'Normal')], default='Normal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('-', '-'), ('Entrada', 'Entrada'), ('Salsa', 'Salsa'), ('Picada', 'Picada'), ('Principal', 'Plato Principal'), ('Postre', 'Postre'), ('Torta', 'Torta'), ('Dip', 'Dip'), ('Trago', 'Trago'), ('Guarnicion', 'Guarnicion')], default='', max_length=20),
        ),
    ]
