# Generated by Django 4.1.7 on 2024-03-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0015_plato_preparacion_alter_plato_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Común', 'Común'), ('Especial', 'Especial')], max_length=20, null=True),
        ),
    ]
