# Generated by Django 4.1.7 on 2024-03-14 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminVideos', '0016_alter_plato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegidos',
            name='nombre_plato_elegido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='elegidos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos_elegidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
