# Generated by Django 5.1.3 on 2024-11-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0016_remove_mensaje_email_mensaje_amistad_profile_amigues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='usuario_que_envia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
