# Generated by Django 5.1.3 on 2024-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0017_mensaje_usuario_que_envia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='nombre_plato_compartido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
