# Generated by Django 5.1.3 on 2024-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0018_mensaje_nombre_plato_compartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sugeridos_descartados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugeridos_importados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
