# Generated by Django 4.1.7 on 2024-03-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0019_platosseleccionados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatosSeleccionados',
        ),
    ]
