# Generated by Django 5.1.3 on 2025-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0019_profile_sugeridos_descartados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='preparacion',
            new_name='dificultad',
        ),
        migrations.AddField(
            model_name='plato',
            name='proviene_de',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
