# Generated by Django 5.0.3 on 2024-03-20 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0020_delete_platosseleccionados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugeridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato_sugerido', models.CharField(max_length=30)),
                ('usuario_de_sugeridos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sugeridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
