# Generated by Django 5.1.3 on 2025-02-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0021_mensaje_leido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preseleccionados',
        ),
    ]
