# Generated by Django 5.0.3 on 2024-03-20 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0021_sugeridos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugeridos',
            name='usuario_de_sugeridos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sugeridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
