# Generated by Django 5.0.3 on 2025-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0022_delete_preseleccionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=400, verbose_name='Ingresá los ingredientes, separados por coma'),
        ),
    ]
