# Generated by Django 5.0.3 on 2024-03-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0022_alter_sugeridos_usuario_de_sugeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='variedades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
