# Generated by Django 5.0.3 on 2025-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0023_plato_id_original_alter_plato_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='borrado_antes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='importado',
            field=models.BooleanField(default=False),
        ),
    ]
