# Generated by Django 5.0.3 on 2025-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0024_mensaje_borrado_antes_mensaje_importado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
