# Generated by Django 5.0.3 on 2025-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0025_plato_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
