# Generated by Django 5.0.3 on 2025-03-30 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0026_plato_direccion_plato_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('dias_horarios', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lugares/', verbose_name='Subí una imagen del lugar')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
