# Generated by Django 5.0.3 on 2025-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0027_remove_plato_direccion_remove_plato_telefono_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Subí una imagen del lugar'),
        ),
    ]
