# Generated by Django 5.0.3 on 2025-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0028_alter_lugar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
    ]
