# Generated by Django 5.0.3 on 2025-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0029_lugar_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mensaje',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='amistad',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='importado',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='nombre_plato_compartido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='id_elemento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tipo_mensaje',
            field=models.CharField(choices=[('amistad', 'amistad'), ('lugar', 'lugar'), ('delivery', 'delivery'), ('plato', 'plato'), ('chat', 'chat')], default='chat', max_length=20, null=True),
        ),
    ]
