# Generated by Django 5.0.3 on 2025-04-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0030_rename_mensaje_mensaje_texto_remove_mensaje_amistad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='importado',
            field=models.BooleanField(default=False),
        ),
    ]
