# Generated by Django 5.0.3 on 2025-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0031_mensaje_importado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='texto',
            new_name='mensaje',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo_mensaje',
            field=models.CharField(choices=[('amistad', 'amistad'), ('lugar', 'lugar'), ('delivery', 'delivery'), ('plato', 'plato'), ('texto', 'texto')], default='texto', max_length=20, null=True),
        ),
    ]
