# Generated by Django 5.0.3 on 2025-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0032_rename_texto_mensaje_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='nombre_elemento_compartido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
