# Generated by Django 5.0.3 on 2025-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0033_mensaje_nombre_elemento_compartido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipo_mensaje',
            field=models.CharField(choices=[('amistad', 'amistad'), ('comerafuera', 'comerafuera'), ('delivery', 'delivery'), ('plato', 'plato'), ('texto', 'texto')], default='texto', max_length=20, null=True),
        ),
    ]
