# Generated by Django 5.0.3 on 2025-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0034_alter_mensaje_tipo_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='dificultad',
        ),
        migrations.AddField(
            model_name='plato',
            name='coccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='elaboracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='estacionalidad',
            field=models.CharField(choices=[('-', '-'), ('Verano', 'Verano'), ('Invierno', 'Invierno'), ('Todo el año', 'Todo el año')], default='Todo el año', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes_detallados',
            field=models.JSONField(blank=True, help_text="Estructura: [{'ingrediente': 'harina', 'cantidad': 200, 'unidad': 'g'}]", null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('-', '-'), ('Cotidiano', 'Cotidiano'), ('Especial', 'Especial')], default='Cotidiano', max_length=20, null=True),
        ),
    ]
