# Generated by Django 5.0.3 on 2025-05-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0035_remove_plato_calorias_remove_plato_dificultad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='platos', to='AdminVideos.tipoplato'),
        ),
    ]
