# Generated by Django 5.0.3 on 2025-05-18 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0036_tipoplato_plato_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteEnPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminVideos.ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_en_plato', to='AdminVideos.plato')),
            ],
        ),
    ]
