# Generated by Django 5.0.3 on 2025-05-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0037_ingrediente_ingredienteenplato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'unidad'), ('gr', 'gr'), ('pizca', 'pizca'), ('mg', 'mg'), ('kg', 'kg'), ('ml', 'ml'), ('cucharada', 'cucharada'), ('cdita', 'cdita')], default='unidad', max_length=20),
        ),
    ]
