# Generated by Django 5.0.3 on 2025-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0038_alter_ingredienteenplato_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='porciones',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de porciones que rinde este plato'),
        ),
    ]
