# Generated by Django 5.0.3 on 2025-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0039_plato_porciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='ingredientes_detallados',
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipos',
            field=models.ManyToManyField(related_name='platos', to='AdminVideos.tipoplato'),
        ),
    ]
