# Generated by Django 5.0.3 on 2025-05-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0040_remove_plato_ingredientes_detallados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='tipo',
        ),
    ]
