# Generated by Django 5.0.3 on 2025-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0043_alter_ingredienteenplato_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='unidad',
            field=models.CharField(choices=[('', '-'), ('unidad', 'unidad'), ('gr', 'gr'), ('pizca', 'pizca'), ('mg', 'mg'), ('kg', 'kg'), ('ml', 'ml'), ('cucharada', 'cucharada'), ('cdita', 'cdita')], default='-', max_length=20),
        ),
    ]
