# Generated by Django 5.0.3 on 2025-05-24 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0044_alter_ingredienteenplato_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminVideos.ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='unidad',
            field=models.CharField(blank=True, choices=[('', '-'), ('unidad', 'unidad'), ('gr', 'gr'), ('pizca', 'pizca'), ('mg', 'mg'), ('kg', 'kg'), ('ml', 'ml'), ('cucharada', 'cucharada'), ('cdita', 'cdita')], default='-', max_length=20, null=True),
        ),
    ]
