# Generated by Django 5.0.3 on 2025-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0045_alter_ingredienteenplato_ingrediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='unidad',
            field=models.CharField(blank=True, choices=[('unidad', 'unidad'), ('gr', 'gr'), ('pizca', 'pizca'), ('mg', 'mg'), ('kg', 'kg'), ('ml', 'ml'), ('cucharada', 'cucharada'), ('cdita', 'cdita')], default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='estacionalidad',
            field=models.CharField(choices=[('Verano', 'Verano'), ('Invierno', 'Invierno'), ('Todo el año', 'Todo el año')], default='Todo el año', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='medios',
            field=models.CharField(choices=[('Horno', 'Horno'), ('Cocina', 'Cocina'), ('Parrilla', 'Parrilla'), ('Wok', 'Wok'), ('Sin coccion', 'Sin cocción')], default='Cocina', max_length=20, null=True),
        ),
    ]
