# Generated by Django 5.0.3 on 2025-05-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0046_alter_ingredienteenplato_unidad_and_more'),
    ]

    operations = [
    ]
