# Generated by Django 5.0.3 on 2025-05-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0047_precargar_tipos_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='tipos',
        ),
        migrations.AddField(
            model_name='plato',
            name='tipos',
            field=models.CharField(blank=True, help_text='Seleccioná los tipos (Ej: Entrada,Principal,Postre)', max_length=200),
        ),
    ]
