# Generated by Django 5.0.3 on 2025-06-08 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0048_remove_plato_tipos_plato_tipos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('momento', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Merienda', 'Merienda'), ('Cena', 'Cena')], max_length=20)),
                ('variedades', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminVideos.plato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas_del_dia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
