# Generated by Django 5.0.3 on 2025-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0049_comidadeldia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidadeldia',
            name='momento',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20),
        ),
    ]
