# Generated by Django 5.0.3 on 2025-06-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0050_alter_comidadeldia_momento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estacionalidad',
            field=models.CharField(blank=True, choices=[('Verano', 'Verano'), ('Invierno', 'Invierno'), ('Todo el año', 'Todo el año')], default='Todo el año', max_length=20, null=True),
        ),
    ]
