# Generated by Django 5.0.3 on 2025-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0051_alter_plato_estacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='estacionalidad',
            field=models.CharField(choices=[('Verano', 'Verano'), ('Invierno', 'Invierno'), ('Todo el año', 'Todo el año')], default='Todo el año', max_length=20, null=True),
        ),
    ]
