# Generated by Django 5.0.3 on 2025-06-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0052_alter_plato_estacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidadeldia',
            name='elegido',
            field=models.BooleanField(default=True),
        ),
    ]
