# Generated by Django 5.0.3 on 2025-06-16 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0053_comidadeldia_elegido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('almuerzo', models.ManyToManyField(blank=True, related_name='almuerzos', to='AdminVideos.plato')),
                ('cena', models.ManyToManyField(blank=True, related_name='cenas', to='AdminVideos.plato')),
                ('desayuno', models.ManyToManyField(blank=True, related_name='desayunos', to='AdminVideos.plato')),
                ('merienda', models.ManyToManyField(blank=True, related_name='meriendas', to='AdminVideos.plato')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
