# Generated by Django 5.0.3 on 2025-08-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0054_historicodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicodia',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
