# Generated by Django 5.0.3 on 2025-08-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0055_historicodia_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicodia',
            name='ya_sugerido',
            field=models.BooleanField(default=False),
        ),
    ]
