# Generated by Django 5.0.3 on 2025-09-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0056_historicodia_ya_sugerido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicodia',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='historicodia',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='historicodia',
            name='desayuno',
        ),
        migrations.RemoveField(
            model_name='historicodia',
            name='merienda',
        ),
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='unidad',
            field=models.CharField(blank=True, choices=[('-', '-'), ('unidad', 'unidad'), ('gr', 'gr'), ('pizca', 'pizca'), ('mg', 'mg'), ('kg', 'kg'), ('ml', 'ml'), ('cucharada', 'cucharada'), ('cdita', 'cdita')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('Ambos', 'Ambos'), ('Cotidiano', 'Cotidiano'), ('Especial', 'Especial')], default='Cotidiano', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_id_ref', models.IntegerField()),
                ('momento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminVideos.historicodia')),
            ],
            options={
                'unique_together': {('historico', 'plato_id_ref', 'momento')},
            },
        ),
    ]
