# Generated by Django 5.0.3 on 2025-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0057_remove_historicodia_almuerzo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugeridos',
            name='usuario_de_sugeridos',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('verduleria', 'Verdulería'), ('carniceria', 'Carnicería'), ('almacen', 'Almacén'), ('panaderia', 'Panadería'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.DeleteModel(
            name='ComidaDelDia',
        ),
        migrations.DeleteModel(
            name='Sugeridos',
        ),
    ]
