# Generated by Django 5.0.3 on 2025-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0058_remove_sugeridos_usuario_de_sugeridos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='detalle',
            field=models.CharField(blank=True, choices=[('Verdulería', [('verdura', 'Verdura'), ('fruta', 'Fruta'), ('tuberculo', 'Tubérculo'), ('hierba_fresca', 'Hierba fresca')]), ('Carnicería', [('carne_roja', 'Carne roja'), ('ave', 'Ave'), ('cerdo', 'Cerdo'), ('cordero', 'Cordero'), ('achuras', 'Achuras')]), ('Pescadería', [('pescado_blanco', 'Pescado blanco'), ('pescado_azul', 'Pescado azul'), ('marisco', 'Marisco')]), ('Panadería', [('pan', 'Pan'), ('facturas', 'Facturas'), ('masa', 'Masa'), ('galletas', 'Galletas')]), ('Almacén', [('legumbre', 'Legumbre'), ('cereal', 'Cereal'), ('harina', 'Harina'), ('aceite', 'Aceite'), ('conserva', 'Conserva'), ('azucar', 'Azúcar'), ('fideos', 'Fideos')]), ('Lácteos', [('leche', 'Leche'), ('queso', 'Queso'), ('yogur', 'Yogur'), ('crema', 'Crema'), ('manteca', 'Manteca')]), ('Condimentos', [('especia', 'Especia'), ('hierba_seca', 'Hierba seca'), ('aderezo', 'Aderezo'), ('salsa', 'Salsa')]), ('Bebidas', [('alcoholica', 'Alcohólica'), ('sin_alcohol', 'Sin alcohol'), ('infusion', 'Infusión')]), ('Otro', [('otro', 'Otro')])], help_text='Subcategoría (p. ej., Verdura, Fruta, Legumbre…).', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(help_text='Nombre del ingrediente (p. ej., Zanahoria, Lentejas).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('verduleria', 'Verdulería'), ('carniceria', 'Carnicería'), ('pescaderia', 'Pescadería'), ('panaderia', 'Panadería'), ('almacen', 'Almacén'), ('lacteos', 'Lácteos'), ('condimentos', 'Condimentos'), ('bebidas', 'Bebidas'), ('otro', 'Otro')], default='otro', help_text='Lugar de compra / categoría general.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ingrediente',
            index=models.Index(fields=['nombre'], name='AdminVideos_nombre_815b19_idx'),
        ),
    ]
