# Generated by Django 5.0.3 on 2025-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0059_alter_ingrediente_options_ingrediente_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='detalle',
            field=models.CharField(blank=True, choices=[('Verdulería', [('verdura', 'Verdura'), ('fruta', 'Fruta'), ('tuberculo', 'Tubérculo'), ('hierba_fresca', 'Hierba fresca')]), ('Carnicería', [('carne_roja', 'Carne roja'), ('ave', 'Ave'), ('cerdo', 'Cerdo'), ('cordero', 'Cordero'), ('achuras', 'Achuras')]), ('Pescadería', [('pescado', 'Pescado'), ('marisco', 'Marisco')]), ('Panadería', [('pan', 'Pan')]), ('Almacén', [('legumbre', 'Legumbre'), ('cereal', 'Cereal'), ('harina_blanca', 'Harina Blanca'), ('aceite', 'Aceite'), ('conserva', 'Conserva'), ('azucar', 'Azúcar'), ('especia', 'Especia')]), ('Condimentos', [('especia', 'Especia')]), ('Otro', [('otro', 'Otro')])], help_text='Subcategoría (p. ej., Verdura, Fruta, Legumbre…).', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('verduleria', 'Verdulería'), ('fiambreria', 'Fiambriería'), ('carniceria', 'Carnicería'), ('pescaderia', 'Pescadería'), ('panaderia', 'Panadería'), ('almacen', 'Almacén'), ('lacteos', 'Lácteos'), ('bebidas', 'Bebidas'), ('otro', 'Otro')], default='otro', help_text='Lugar de compra / categoría general.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredienteenplato',
            name='unidad',
            field=models.CharField(blank=True, choices=[('-', '-'), ('unidad', 'unidad'), ('gr', 'gramo'), ('kg', 'kilogramo'), ('mg', 'miligramo'), ('ml', 'mililitro'), ('l', 'litro'), ('cdita', 'cucharadita'), ('cda', 'cucharada'), ('taza', 'taza'), ('pizca', 'pizca')], default='-', max_length=20),
        ),
    ]
