# Generated by Django 5.0.3 on 2025-09-27 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0060_profile_share_token_alter_ingrediente_detalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicodia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plato',
            name='proviene_de',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='historicodia',
            unique_together={('fecha', 'propietario')},
        ),
    ]
