# Generated by Django 5.0.3 on 2025-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0061_alter_historicodia_fecha_alter_plato_proviene_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ingredientes_a_comprar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
