# Generated by Django 5.0.3 on 2025-09-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0062_profile_ingredientes_a_comprar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ingredientes_a_comprar',
        ),
    ]
