# Generated by Django 5.0.3 on 2025-12-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0063_remove_profile_ingredientes_a_comprar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='descripcion_plato',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='detalle',
            field=models.CharField(blank=True, choices=[('Verdulería', [('verdura', 'Verdura'), ('fruta', 'Fruta'), ('tuberculo', 'Tubérculo'), ('hierba_fresca', 'Hierba fresca')]), ('Carnicería', [('carne_roja', 'Carne roja'), ('ave', 'Ave'), ('cerdo', 'Cerdo'), ('cordero', 'Cordero'), ('achuras', 'Achuras')]), ('Pescadería', [('pescado', 'Pescado'), ('marisco', 'Marisco')]), ('Panadería', [('pan', 'Pan')]), ('Almacén', [('legumbre', 'Legumbre'), ('cereal', 'Cereal'), ('harina_blanca', 'Harina Blanca'), ('aceite', 'Aceite'), ('conserva', 'Conserva'), ('azucar', 'Azúcar'), ('especia', 'Especia')]), ('Condimentos', [('especia', 'Especia'), ('Condimento', 'Condimento')]), ('Otro', [('otro', 'Otro')])], help_text='Subcategoría (p. ej., Verdura, Fruta, Legumbre…).', max_length=30),
        ),
    ]
