# Generated by Django 5.0.3 on 2025-10-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0063_remove_profile_ingredientes_a_comprar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='descripcion_plato',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='detalle',
            field=models.CharField(blank=True, choices=[('Verdulería', [('verdura', 'Verdura'), ('fruta', 'Fruta'), ('tuberculo', 'Tubérculo'), ('hierba_fresca', 'Hierba fresca')]), ('Carnicería', [('carne_roja', 'Carne roja'), ('ave', 'Ave'), ('cerdo', 'Cerdo'), ('cordero', 'Cordero'), ('achuras', 'Achuras')]), ('Pescadería', [('pescado', 'Pescado'), ('marisco', 'Marisco')]), ('Panadería', [('pan', 'Pan')]), ('Almacén', [('legumbre', 'Legumbre'), ('cereal', 'Cereal'), ('harina_blanca', 'Harina Blanca'), ('aceite', 'Aceite'), ('conserva', 'Conserva'), ('azucar', 'Azúcar'), ('especia', 'Especia')]), ('Condimentos', [('especia', 'Especia'), ('Condimento', 'Condimento')]), ('Otro', [('otro', 'Otro')])], help_text='Subcategoría (p. ej., Verdura, Fruta, Legumbre…).', max_length=30),
        ),
        migrations.CreateModel(
            name='VariedadPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(blank=True, max_length=400)),
                ('elaboracion', models.IntegerField(blank=True, null=True)),
                ('coccion', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variedades/')),
                ('activo', models.BooleanField(default=True)),
                ('plato_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades_nuevas', to='AdminVideos.plato')),
            ],
        ),
    ]
