# Generated by Django 5.0.3 on 2026-01-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0064_remove_plato_descripcion_plato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='plato_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variedades_hijas', to='AdminVideos.plato'),
        ),
    ]
