# Generated by Django 5.0.3 on 2026-01-06 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0065_plato_plato_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ya_sugerido', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_dia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_menus', to='AdminVideos.lugar')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminVideos.menudia')),
                ('plato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_menus', to='AdminVideos.plato')),
            ],
        ),
        migrations.AddIndex(
            model_name='menudia',
            index=models.Index(fields=['propietario', 'fecha'], name='AdminVideos_propiet_31a7d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menudia',
            unique_together={('propietario', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu', 'momento'], name='AdminVideos_menu_id_c65981_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['plato'], name='AdminVideos_plato_i_2ba1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['lugar'], name='AdminVideos_lugar_i_aa6491_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('plato__isnull', False)), fields=('menu', 'momento', 'plato'), name='uq_menu_momento_plato'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('lugar__isnull', False)), fields=('menu', 'momento', 'lugar'), name='uq_menu_momento_lugar'),
        ),
    ]
