# Generated by Django 5.0.3 on 2026-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0066_menudia_menuitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='elegido',
            field=models.BooleanField(default=True),
        ),
    ]
