# Generated by Django 5.0.3 on 2026-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0067_menuitem_elegido'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='nombre_grupo',
            field=models.CharField(blank=True, help_text='Nombre del grupo de variedades (ej: Empanadas)', max_length=50),
        ),
    ]
