# Generated by Django 5.0.3 on 2026-01-18 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0068_plato_nombre_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tengo', models.BooleanField(default=True)),
                ('comentario', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_bought_at', models.DateTimeField(blank=True, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_pantry_de', to='AdminVideos.ingrediente')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_pantry', to='AdminVideos.profile')),
            ],
            options={
                'unique_together': {('profile', 'ingrediente')},
            },
        ),
    ]
