# Generated by Django 5.0.3 on 2026-01-18 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0069_profileingrediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('estado', models.CharField(choices=[('tengo', 'Tengo'), ('no-tengo', 'No tengo'), ('recien-comprado', 'Recién comprado')], default='no-tengo', max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('estado_hasta', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_estado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'estado'], name='AdminVideos_user_id_d71fc2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ingredienteestado',
            constraint=models.UniqueConstraint(fields=('user', 'nombre'), name='uniq_user_ingrediente_nombre'),
        ),
    ]
