# Generated by Django 5.0.3 on 2026-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0070_ingredienteestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileingrediente',
            name='tengo',
            field=models.BooleanField(default=False),
        ),
    ]
