# Generated by Django 5.0.3 on 2026-01-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0071_alter_profileingrediente_tengo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElegidosXDia',
        ),
    ]
