# Generated by Django 5.0.3 on 2026-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0072_delete_elegidosxdia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ingredientes_que_tengo',
        ),
    ]
