# Generated by Django 5.0.3 on 2026-01-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0073_remove_profile_ingredientes_que_tengo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='variedades',
        ),
    ]
