# Generated by Django 5.0.3 on 2026-01-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0074_remove_plato_variedades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comentarios',
        ),
    ]
