# Generated by Django 5.0.3 on 2026-01-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0075_remove_profile_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='fijo',
            field=models.BooleanField(default=False),
        ),
    ]
