# Generated by Django 5.0.3 on 2026-01-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0076_menuitem_fijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='fijo',
        ),
        migrations.CreateModel(
            name='HabitoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('momento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos_semanales', to='AdminVideos.profile')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminVideos.plato')),
            ],
            options={
                'unique_together': {('perfil', 'dia_semana', 'momento', 'plato')},
            },
        ),
    ]
