# Generated by Django 5.0.3 on 2026-01-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0077_remove_menuitem_fijo_habitosemanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipos',
            field=models.CharField(help_text='Seleccioná los tipos (Ej: Entrada,Principal,Postre)', max_length=200),
        ),
        migrations.CreateModel(
            name='MenuItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('guarnicion', 'Guarnición'), ('salsa', 'Salsa'), ('postre', 'Postre')], max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='AdminVideos.menuitem')),
            ],
            options={
                'ordering': ['tipo', 'orden', 'id'],
            },
        ),
    ]
