# Generated by Django 5.0.3 on 2026-01-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0078_alter_plato_tipos_menuitemextra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicoitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='historicoitem',
            name='historico',
        ),
        migrations.DeleteModel(
            name='HistoricoDia',
        ),
        migrations.DeleteModel(
            name='HistoricoItem',
        ),
    ]
