# Generated by Django 5.0.3 on 2026-02-01 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0080_alter_ingrediente_detalle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitosemanal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habitosemanal',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminVideos.lugar'),
        ),
        migrations.AlterField(
            model_name='habitosemanal',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminVideos.plato'),
        ),
        migrations.AddConstraint(
            model_name='habitosemanal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('plato__isnull', False), ('lugar__isnull', True)), models.Q(('plato__isnull', True), ('lugar__isnull', False)), _connector='OR'), name='habito_exactamente_un_objeto'),
        ),
        migrations.AddConstraint(
            model_name='habitosemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('plato__isnull', False)), fields=('perfil', 'dia_semana', 'momento', 'plato'), name='uniq_habito_plato'),
        ),
        migrations.AddConstraint(
            model_name='habitosemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('lugar__isnull', False)), fields=('perfil', 'dia_semana', 'momento', 'lugar'), name='uniq_habito_lugar'),
        ),
    ]
