# Generated by Django 5.0.3 on 2026-02-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0081_alter_habitosemanal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='en_menus', to='AdminVideos.lugar'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='en_menus', to='AdminVideos.plato'),
        ),
    ]
