# Generated by Django 5.0.3 on 2026-02-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0082_alter_menuitem_lugar_alter_menuitem_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_menus', to='AdminVideos.lugar'),
        ),
    ]
