# Generated by Django 5.0.3 on 2026-02-03 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0084_alter_menuitem_plato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienteestado',
            name='estado_hasta',
        ),
        migrations.AddField(
            model_name='ingredienteestado',
            name='last_bought_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ingredienteestado',
            index=models.Index(fields=['user', 'last_bought_at'], name='AdminVideos_user_id_f65b8a_idx'),
        ),
    ]
