# Generated by Django 5.0.3 on 2026-02-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0085_remove_ingredienteestado_estado_hasta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredienteEstado',
        ),
    ]
