# Generated by Django 5.0.3 on 2026-03-01 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0086_delete_ingredienteestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_armado', models.CharField(choices=[('Picada', 'Picada'), ('Ensalada', 'Ensalada')], max_length=30)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='armados', to='AdminVideos.plato')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
