# Generated by Django 5.0.3 on 2026-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0087_armado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='componentes',
            field=models.ManyToManyField(blank=True, help_text='Otros platos que componen este plato', related_name='forma_parte_de', to='AdminVideos.plato'),
        ),
    ]
