# Generated by Django 5.0.3 on 2026-05-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0088_plato_componentes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armado',
        ),
    ]
