# Generated by Django 5.0.3 on 2026-06-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0089_delete_armado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='ingredientes',
            field=models.CharField(blank=True, help_text='Campo legacy. Se conserva temporalmente como texto derivado de IngredienteEnPlato.', max_length=400, verbose_name='Ingredientes legacy, separados por coma'),
        ),
        migrations.CreateModel(
            name='ProfilePlatoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elegido', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_compra', to='AdminVideos.profile')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_compra', to='AdminVideos.plato')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profileplatocompra',
            constraint=models.UniqueConstraint(fields=('perfil', 'plato'), name='uq_profile_plato_compra'),
        ),
    ]
