# Generated by Django 5.0.3 on 2026-06-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0090_alter_plato_ingredientes_profileplatocompra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plato', 'Plato'), ('lugar', 'Lugar')], max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('importado', 'Importado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_compartidos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartidos_recibidos_como_lugar', to='AdminVideos.lugar')),
                ('plato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartidos_recibidos_como_plato', to='AdminVideos.plato')),
                ('plato_importado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartidos_importados_desde', to='AdminVideos.plato')),
                ('usuario_que_envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_compartidos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='elementocompartido',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lugar__isnull', True), ('plato__isnull', False), ('tipo', 'plato')), models.Q(('lugar__isnull', False), ('plato__isnull', True), ('tipo', 'lugar')), _connector='OR'), name='elemento_compartido_tiene_un_solo_objeto'),
        ),
    ]
