# Generated by Django 5.0.3 on 2026-06-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0091_elementocompartido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_como_usuario_1', to=settings.AUTH_USER_MODEL)),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_como_usuario_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='amistad',
            constraint=models.UniqueConstraint(fields=('usuario_1', 'usuario_2'), name='uq_amistad_usuarios'),
        ),
        migrations.AddConstraint(
            model_name='amistad',
            constraint=models.CheckConstraint(check=models.Q(('usuario_1', models.F('usuario_2')), _negated=True), name='amistad_usuarios_distintos'),
        ),
    ]
