# Generated by Django 5.0.3 on 2026-06-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0092_amistad_amistad_uq_amistad_usuarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='id_elemento',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='importado',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='nombre_elemento_compartido',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='tipo_mensaje',
        ),
    ]
