# Generated by Django 5.0.3 on 2026-06-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0093_remove_mensaje_id_elemento_remove_mensaje_importado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amigues',
        ),
    ]
