# Generated by Django 5.0.3 on 2026-06-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0095_mensaje_usuario_que_envia_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario_que_envia',
        ),
    ]
