# Generated by Django 5.0.3 on 2026-06-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0096_remove_mensaje_usuario_que_envia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoQueTengoPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=60)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_lo_que_tengo', to='AdminVideos.profile')),
            ],
            options={
                'ordering': ['palabra'],
            },
        ),
    ]
