# Generated by Django 5.0.3 on 2026-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminVideos', '0097_loquetengopalabra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='receta',
            field=models.TextField(blank=True),
        ),
    ]
